# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:1.17-alpine

variables:
  # Please edit to your GitLab project
  REPO_NAME: git.ftb.dev/Jake_Evans/ftb-debug

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - build
  - deploy

build linux:
  stage: build
  variables:
    GOOS: linux
  script:
    - go build -ldflags "-X main.GitCommit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/ftb-debug-linux
  artifacts:
    paths:
      - ftb-debug-linux

build windows:
  stage: build
  variables:
    GOOS: windows
  script:
    - go build -ldflags "-X main.GitCommit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/ftb-debug.exe
  artifacts:
    paths:
      - ftb-debug.exe

build windowsArm:
  stage: build
  variables:
    GOOS: windows
    GOARCH: arm64
  script:
    - go build -ldflags "-X main.GitCommit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/ftb-debug-arm64.exe
  artifacts:
    paths:
      - ftb-debug-arm64.exe


build macos:
  stage: build
  variables:
    GOOS: darwin
  script:
    - go build -ldflags "-X main.GitCommit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/ftb-debug-macos
  artifacts:
    paths:
      - ftb-debug-macos

build macos-m1:
  stage: build
  variables:
    GOOS: darwin
    GOARCH: arm64
  script:
    - go build -ldflags "-X main.GitCommit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/ftb-debug-macos-arm64
  artifacts:
    paths:
      - ftb-debug-macos-arm64