name: "Setup Common"
description: "Common setup for all builds"
runs:
  using: "composite"
  steps:
    - name: Short SHA
      shell: bash
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - name: Setup Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
        cache-dependency-path: go.sum

    - name: Install dependencies
      shell: bash
      run: |
        go get .

    - name: Run tests
      shell: bash
      run: |
        go test ./...