// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCommonFixes():Promise<void>;

export function RunDebug():Promise<string>;
