// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCommonFixes() {
  return window['go']['backend']['App']['RunCommonFixes']();
}

export function RunDebug() {
  return window['go']['backend']['App']['RunDebug']();
}
