name: "Snapshot Build"
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-all:
    name: Build and release all platforms
    runs-on: ubuntu-latest
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: "Common Setup"

      - name: Doctor
        run: |
          wails doctor

      - name: Build
        run: |
          make build_all

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          path: |
            out/*