name: "Snapshot Build"
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    name: Build snapshot Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [ windows ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: "Common Setup"

      - name: Doctor
        run: |
          wails doctor

      - name: Build
        run: |
          wails build -clean -platform ${{ matrix.goos }}/${{ matrix.goarch }} -trimpath -ldflags "-s -w -X 'main.GitCommit=$(GITHUB_SHA_SHORT)' -X 'main.Version=$(GITHUB_REF_NAME)'"
          mkdir -p ./out
          mv ./build/bin/ftb-debug-ui.exe ./out/ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}.exe

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          path: |
            out/*

  build-linux:
    name: Build snapshot Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [ linux ]
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: "Common Setup"

      - name: Doctor
        run: |
          wails doctor

      - name: Build
        run: |
          wails build -clean -platform ${{ matrix.goos }}/${{ matrix.goarch }} -trimpath -ldflags "-s -w -X 'main.GitCommit=$(GITHUB_SHA_SHORT)' -X 'main.Version=$(GITHUB_REF_NAME)'"
          mkdir -p ./out
          mv ./build/bin/ftb-debug-ui ./out/ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          path: |
            out/*

  build-macos:
    name: Build snapshot macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [ darwin ]
        goarch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: "Common Setup"

      - name: Doctor
        run: |
          wails doctor

      - name: Build
        run: |
          wails build -clean -platform ${{ matrix.goos }}/${{ matrix.goarch }} -trimpath -ldflags "-s -w -X 'shared.GitCommit=$(GITHUB_SHA_SHORT)' -X 'shared.Version=$(GITHUB_REF_NAME)'"
          mkdir -p ./out
          cd ./build/bin; zip -r ../../out/ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}.zip ftb-debug-ui.app

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ftb-debug-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
          path: |
            out/*